spring:
  application:
    name: user-consumer-ribbon
server:
  port: 10211
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true     # 在应用中显示 IP
# 通过配置文件的方式指定服务的负载均衡算法
#user-provider:
#  ribbon:
#    NFLoadBalancerRuleClassName:com.netflix.loadbalancer.RandomRule

# 禁用 ribbon，禁用后就需要自己实现负载均衡
#ribbon:
#  eureka:
#    enabled: false
