spring:
  application:
    name: eureka-ha
  profiles:
    active: peer2
server:
  port: 10012
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:10011/eureka,http://peer3:10013/eureka
