spring:
  application:
    name: eureka-ha
  profiles:
    active: peer3
server:
  port: 10013
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer1:10011/eureka,http://peer2:10012/eureka
