server:
  port: 10501
spring:
  application:
    name: springcloud-config-server-eureka

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/binarylei/spring-cloud-config
          search-paths:
            - app1
            - app2
          clone-on-start: true # 启动就加载文件

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka