spring:
  application:
    name: user-consumer-feign-hystrix
server:
  port: 10303
eureka:
  client:
    service-url:
      defaultZone: http://peer1:10011/eureka
  instance:
    prefer-ip-address: true     # 在应用中显示 IP
feign:
  hystrix:
    enabled: true
