server:
  port: 10500
spring:
  application:
    name: spring-cloud-config

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/binarylei/spring-cloud-config

  # 认证，需要引入 spring-boot-starter-security
  security:
    basic:
      enabled: true
    user:
      name: user
      password: 123
