spring:
  application:
    name: eureka-ha
server:
  port: 10013
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:10011/eureka,http://localhost:10012/eureka
